kind: Product
apiVersion: api.ibm.com/v1
metadata:
  name: producto-pagos
  namespace: API_Pagos
  version: '1.0'
  tags: []
  description: ''
spec:
  apis:
    - $ref: apipagos:API_Pagos:1.0
  plans: []
